apiVersion: v1
kind: Pod
metadata:
  name: test-pod

spec:
  containers:
    - name: test
      image: nginx
  env:
    - name: Course
      value: K8S
    - name: Duration
      value: 6 Months
    - name: Instructor
      value: Shiva

# kubectl apply -f envoirment.yaml
# kubectl get pods
# kubectl describe envoirment.yaml
# kubectl delete envoirment.yaml
    