apiVersion: v1
kind: Pod
metadata:
  name: multicontainer-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
    - name: almalinux
      image: almalinux:9
      ports:
        - containerPort: 8080
      command: ["/bin/bash", "-c", "while true; do echo 'Hello from AlmaLinux'; sleep 5; done"]

# kubectl apply -f K8S/Multicontainer.yaml
# kubectl get pods
# kubectl describe pod multicontainer-pod
# kubectl delete pod multicontainer-pod
# kubectl exec -it multicontainer-pod -c almalinux -- /bin/bash
# kubectl exec -it multicontainer-pod -c nginx -- /bin/bash