apiVersion: v1
kind: pod
metadata:
  name: nginx # Name of the pod
  namespace: xius-dev 
  labels:
    name: nginx
    project: tunetalk
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

# Validate the YAML
kubectl apply --dry-run=client -f 02_pod.yaml

# Create the Pod
kubectl apply -f 02_pod.yaml

# Check the Pod
kubectl get pods -n xius-dev

# Check Pod with more details
kubectl get pod nginx -n xius-dev -o wide

# Describe the Pod
kubectl describe pod nginx -n xius-dev

# Check Pod logs
kubectl logs nginx -n xius-dev
